"""add shipment event table

Revision ID: 1c8d5302b38f
Revises: 8800db418d3a
Create Date: 2026-06-12 22:25:24.781000

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8d5302b38f'
down_revision: Union[str, Sequence[str], None] = '8800db418d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_partner', 'address')
    op.add_column('seller', sa.Column('zip_code', sa.Integer(), nullable=True))
    op.alter_column('seller', 'address',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'address',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('seller', 'zip_code')
    op.add_column('delivery_partner', sa.Column('address', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
