"""add tag

Revision ID: 97bc13bfc4a3
Revises: 80fd128d76fd
Create Date: 2026-07-03 22:50:16.918974

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97bc13bfc4a3'
down_revision: Union[str, Sequence[str], None] = '80fd128d76fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTR0LLED', 'GIFT', 'RETURN', 'DOCUMENTS', name='tagname'), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    
    # Seed default tag values
    import uuid
    op.execute(
        "INSERT INTO tag (id, name, instruction) VALUES "
        f"('{uuid.uuid4()}', 'EXPRESS', 'Deliver within 24 hours'),"
        f"('{uuid.uuid4()}', 'STANDARD', 'Deliver within 3-5 business days'),"
        f"('{uuid.uuid4()}', 'FRAGILE', 'Handle with care, do not drop'),"
        f"('{uuid.uuid4()}', 'HEAVY', 'Requires two people to lift'),"
        f"('{uuid.uuid4()}', 'INTERNATIONAL', 'Requires customs clearance inspection'),"
        f"('{uuid.uuid4()}', 'DOMESTIC', 'Standard domestic transport regulations apply'),"
        f"('{uuid.uuid4()}', 'TEMPERATURE_CONTR0LLED', 'Keep refrigerated/under temperature control'),"
        f"('{uuid.uuid4()}', 'GIFT', 'Do not disclose price, gift wrapping included'),"
        f"('{uuid.uuid4()}', 'RETURN', 'Return shipment to sender address'),"
        f"('{uuid.uuid4()}', 'DOCUMENTS', 'Contains critical documentation, keep flat')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag')
    op.drop_table('review')
    op.drop_table('tag')
    # ### end Alembic commands ###
