"""update shipment_event

Revision ID: b580c3912f7c
Revises: 1c8d5302b38f
Create Date: 2026-06-13 23:27:58.105878

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b580c3912f7c'
down_revision: Union[str, Sequence[str], None] = '1c8d5302b38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipment_event', sa.Column('location', sa.Integer(), nullable=False))
    op.add_column('shipment_event', sa.Column('status', sa.Enum('placed', 'in_transit', 'out_for_delivery', 'delivered', name='shipmentstatus'), nullable=False))
    op.add_column('shipment_event', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipment_event', 'description')
    op.drop_column('shipment_event', 'status')
    op.drop_column('shipment_event', 'location')
    # ### end Alembic commands ###
