"""sync models with database

Revision ID: dde5feadb42a
Revises: 97bc13bfc4a3
Create Date: 2026-07-15 21:59:50.272821

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dde5feadb42a'
down_revision: Union[str, Sequence[str], None] = '97bc13bfc4a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_partner', 'serviceable_zip_codes')
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shipment', 'estimated_delivery',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('shipment', 'delivery_partner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('shipment', 'status')
    op.alter_column('shipment_event', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipment_event', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('shipment', sa.Column('status', postgresql.ENUM('placed', 'in_transit', 'out_for_delivery', 'delivered', 'cancelled', name='shipmentstatus'), autoincrement=False, nullable=False))
    op.alter_column('shipment', 'delivery_partner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('shipment', 'estimated_delivery',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('seller', 'zip_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('seller', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('delivery_partner', sa.Column('serviceable_zip_codes', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
